CREATE DATABASE IF NOT EXISTS lab_mysql;

USE lab_mysql;

CREATE TABLE IF NOT EXISTS `Customers` (
	`Customer_ID` VARCHAR(255) NOT NULL UNIQUE,
	`Name` VARCHAR(255) NOT NULL,
	`Phone_Number` VARCHAR(255) NOT NULL,
	`Email` VARCHAR(255) NOT NULL,
	`Address` VARCHAR(255) NOT NULL,
	`City` VARCHAR(255) NOT NULL,
	`State` VARCHAR(255) NOT NULL,
	`Country` VARCHAR(255) NOT NULL,
	`Postalcode` VARCHAR(255) NOT NULL,
	PRIMARY KEY(`Customer_ID`)
);

CREATE TABLE IF NOT EXISTS `Cars` ( 
	`VIN` VARCHAR(255) NOT NULL UNIQUE,
    'Customer_ID' VARCHAR (255) UNIQUE, 
 	`manufacturer` VARCHAR(255) NOT NULL,
	`model` VARCHAR(255) NOT NULL,
	`year` YEAR NOT NULL,
	`color` VARCHAR(255) NOT NULL,
	PRIMARY KEY(`Customer_ID`)
) ;


CREATE TABLE IF NOT EXISTS `Salespersons` (
	`Staff_ID` VARCHAR(255) NOT NULL UNIQUE,
	`Name` VARCHAR(255) NOT NULL,
	`Store` VARCHAR(255) NOT NULL,
	PRIMARY KEY(`Staff_ID`)
);


CREATE TABLE IF NOT EXISTS `Invoices` (
	`Invoice_NO` VARCHAR(255) NOT NULL UNIQUE,
	`Date` DATE NOT NULL,
	`Car` VARCHAR(255) NOT NULL,
	`Customer` VARCHAR(255) NOT NULL,
	`Salesperson` VARCHAR(255) NOT NULL,
	PRIMARY KEY(`Invoice_NO`)
);
